[package]
name = "streamer-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rust-s3 = "0.27.0-rc4"
serde = { version = "1.0.209", features = ["derive"] }
actix-cors = "0.7.0"
futures = "0.3.30"
actix-easy-multipart = "3.0.0"
rand = "0.8.5"

